shopify_app:
  name: "Juice Society Shipping"
  scopes:
    - "read_products"
    - "read_shipping"
    - "write_shipping"
    - "read_checkouts"
    - "write_checkouts"
    - "read_price_rules"
  webhooks:
    - "some_webhook"
